// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_normal_pdf
void test_normal_pdf();
RcppExport SEXP _ViralLoadRJMCMC_test_normal_pdf() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_normal_pdf();
    return R_NilValue;
END_RCPP
}
// test_normal_cdf
void test_normal_cdf();
RcppExport SEXP _ViralLoadRJMCMC_test_normal_cdf() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_normal_cdf();
    return R_NilValue;
END_RCPP
}
// test_exp_pdf
void test_exp_pdf();
RcppExport SEXP _ViralLoadRJMCMC_test_exp_pdf() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_exp_pdf();
    return R_NilValue;
END_RCPP
}
// test_exp_cdf
void test_exp_cdf();
RcppExport SEXP _ViralLoadRJMCMC_test_exp_cdf() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_exp_cdf();
    return R_NilValue;
END_RCPP
}
// log_likelihood_ti
double log_likelihood_ti(double y_i, double t_i, double wp_i, double tp_i, double dp_i, double wr_i, double sigma, double sensitivity);
RcppExport SEXP _ViralLoadRJMCMC_log_likelihood_ti(SEXP y_iSEXP, SEXP t_iSEXP, SEXP wp_iSEXP, SEXP tp_iSEXP, SEXP dp_iSEXP, SEXP wr_iSEXP, SEXP sigmaSEXP, SEXP sensitivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y_i(y_iSEXP);
    Rcpp::traits::input_parameter< double >::type t_i(t_iSEXP);
    Rcpp::traits::input_parameter< double >::type wp_i(wp_iSEXP);
    Rcpp::traits::input_parameter< double >::type tp_i(tp_iSEXP);
    Rcpp::traits::input_parameter< double >::type dp_i(dp_iSEXP);
    Rcpp::traits::input_parameter< double >::type wr_i(wr_iSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sensitivity(sensitivitySEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_ti(y_i, t_i, wp_i, tp_i, dp_i, wr_i, sigma, sensitivity));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood
double log_likelihood(viral_data_struct& viral_data, current_data_struct& current_data, current_parameters_struct& current_parameters, settings_struct& settings);
RcppExport SEXP _ViralLoadRJMCMC_log_likelihood(SEXP viral_dataSEXP, SEXP current_dataSEXP, SEXP current_parametersSEXP, SEXP settingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< viral_data_struct& >::type viral_data(viral_dataSEXP);
    Rcpp::traits::input_parameter< current_data_struct& >::type current_data(current_dataSEXP);
    Rcpp::traits::input_parameter< current_parameters_struct& >::type current_parameters(current_parametersSEXP);
    Rcpp::traits::input_parameter< settings_struct& >::type settings(settingsSEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood(viral_data, current_data, current_parameters, settings));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _ViralLoadRJMCMC_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// mu
double mu(double t, double wp, double tp, double dp, double wr);
RcppExport SEXP _ViralLoadRJMCMC_mu(SEXP tSEXP, SEXP wpSEXP, SEXP tpSEXP, SEXP dpSEXP, SEXP wrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type wp(wpSEXP);
    Rcpp::traits::input_parameter< double >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< double >::type dp(dpSEXP);
    Rcpp::traits::input_parameter< double >::type wr(wrSEXP);
    rcpp_result_gen = Rcpp::wrap(mu(t, wp, tp, dp, wr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ViralLoadRJMCMC_test_normal_pdf", (DL_FUNC) &_ViralLoadRJMCMC_test_normal_pdf, 0},
    {"_ViralLoadRJMCMC_test_normal_cdf", (DL_FUNC) &_ViralLoadRJMCMC_test_normal_cdf, 0},
    {"_ViralLoadRJMCMC_test_exp_pdf", (DL_FUNC) &_ViralLoadRJMCMC_test_exp_pdf, 0},
    {"_ViralLoadRJMCMC_test_exp_cdf", (DL_FUNC) &_ViralLoadRJMCMC_test_exp_cdf, 0},
    {"_ViralLoadRJMCMC_log_likelihood_ti", (DL_FUNC) &_ViralLoadRJMCMC_log_likelihood_ti, 8},
    {"_ViralLoadRJMCMC_log_likelihood", (DL_FUNC) &_ViralLoadRJMCMC_log_likelihood, 4},
    {"_ViralLoadRJMCMC_rcpp_hello_world", (DL_FUNC) &_ViralLoadRJMCMC_rcpp_hello_world, 0},
    {"_ViralLoadRJMCMC_mu", (DL_FUNC) &_ViralLoadRJMCMC_mu, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ViralLoadRJMCMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
