// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rjmcmc_r
void rjmcmc_r(std::string output_dir, std::vector<int> index_arg, std::vector<double> viral_load_arg, std::vector<double> time_arg, std::vector<int> subtype_arg, std::vector<double> t_first_positive_arg, std::vector<double> t_last_positive_arg, std::vector<double> t_first_test_arg, std::vector<double> t_last_test_arg, std::vector<int> n_positive_tests_arg, double lod_arg, double sensitivity_arg, int n_iterations_arg, int n_subtypes_arg, int n_subjects_arg, int n_data_arg, std::vector<double> wp_current_arg, std::vector<double> tp_current_arg, std::vector<double> dp_current_arg, std::vector<double> wr_current_arg, std::vector<int> model_current_arg, double sigma_arg, std::vector<double> wp_mean_arg, std::vector<double> wp_sd_arg, std::vector<double> tp_sd_arg, std::vector<double> dp_mean_arg, std::vector<double> dp_sd_arg, std::vector<double> wr_mean_arg, std::vector<double> wr_sd_arg, double wp_max_arg, double wr_max_arg, double wpmean_max_arg, double dpmean_max_arg, double wrmean_max_arg, double wpsd_max_arg, double tpsd_max_arg, double dpsd_max_arg, double wrsd_max_arg, double sigma_max_arg, double wpsd_min_arg, double tpsd_min_arg, double dpsd_min_arg, double wrsd_min_arg, double sigma_min_arg, double p_model_1_arg, double p_model_2_arg, double p_model_3_arg, double wpmean_mean_arg, double wpmean_sd_arg, double dpmean_mean_arg, double dpmean_sd_arg, double wrmean_mean_arg, double wrmean_sd_arg, double wpsd_scale_arg, double tpsd_scale_arg, double dpsd_scale_arg, double wrsd_scale_arg, double sigma_scale_arg, std::vector<double> wp_mean_sf_arg, std::vector<double> wp_sd_sf_arg, std::vector<double> tp_sd_sf_arg, std::vector<double> dp_mean_sf_arg, std::vector<double> dp_sd_sf_arg, std::vector<double> wr_mean_sf_arg, std::vector<double> wr_sd_sf_arg, double sigma_sf_arg, double wp_sf_arg, double tp_sf_arg, double dp_sf_arg, double wr_sf_arg, double seed_arg);
RcppExport SEXP _ViralLoadRJMCMC_rjmcmc_r(SEXP output_dirSEXP, SEXP index_argSEXP, SEXP viral_load_argSEXP, SEXP time_argSEXP, SEXP subtype_argSEXP, SEXP t_first_positive_argSEXP, SEXP t_last_positive_argSEXP, SEXP t_first_test_argSEXP, SEXP t_last_test_argSEXP, SEXP n_positive_tests_argSEXP, SEXP lod_argSEXP, SEXP sensitivity_argSEXP, SEXP n_iterations_argSEXP, SEXP n_subtypes_argSEXP, SEXP n_subjects_argSEXP, SEXP n_data_argSEXP, SEXP wp_current_argSEXP, SEXP tp_current_argSEXP, SEXP dp_current_argSEXP, SEXP wr_current_argSEXP, SEXP model_current_argSEXP, SEXP sigma_argSEXP, SEXP wp_mean_argSEXP, SEXP wp_sd_argSEXP, SEXP tp_sd_argSEXP, SEXP dp_mean_argSEXP, SEXP dp_sd_argSEXP, SEXP wr_mean_argSEXP, SEXP wr_sd_argSEXP, SEXP wp_max_argSEXP, SEXP wr_max_argSEXP, SEXP wpmean_max_argSEXP, SEXP dpmean_max_argSEXP, SEXP wrmean_max_argSEXP, SEXP wpsd_max_argSEXP, SEXP tpsd_max_argSEXP, SEXP dpsd_max_argSEXP, SEXP wrsd_max_argSEXP, SEXP sigma_max_argSEXP, SEXP wpsd_min_argSEXP, SEXP tpsd_min_argSEXP, SEXP dpsd_min_argSEXP, SEXP wrsd_min_argSEXP, SEXP sigma_min_argSEXP, SEXP p_model_1_argSEXP, SEXP p_model_2_argSEXP, SEXP p_model_3_argSEXP, SEXP wpmean_mean_argSEXP, SEXP wpmean_sd_argSEXP, SEXP dpmean_mean_argSEXP, SEXP dpmean_sd_argSEXP, SEXP wrmean_mean_argSEXP, SEXP wrmean_sd_argSEXP, SEXP wpsd_scale_argSEXP, SEXP tpsd_scale_argSEXP, SEXP dpsd_scale_argSEXP, SEXP wrsd_scale_argSEXP, SEXP sigma_scale_argSEXP, SEXP wp_mean_sf_argSEXP, SEXP wp_sd_sf_argSEXP, SEXP tp_sd_sf_argSEXP, SEXP dp_mean_sf_argSEXP, SEXP dp_sd_sf_argSEXP, SEXP wr_mean_sf_argSEXP, SEXP wr_sd_sf_argSEXP, SEXP sigma_sf_argSEXP, SEXP wp_sf_argSEXP, SEXP tp_sf_argSEXP, SEXP dp_sf_argSEXP, SEXP wr_sf_argSEXP, SEXP seed_argSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type output_dir(output_dirSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type index_arg(index_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type viral_load_arg(viral_load_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type time_arg(time_argSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type subtype_arg(subtype_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type t_first_positive_arg(t_first_positive_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type t_last_positive_arg(t_last_positive_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type t_first_test_arg(t_first_test_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type t_last_test_arg(t_last_test_argSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_positive_tests_arg(n_positive_tests_argSEXP);
    Rcpp::traits::input_parameter< double >::type lod_arg(lod_argSEXP);
    Rcpp::traits::input_parameter< double >::type sensitivity_arg(sensitivity_argSEXP);
    Rcpp::traits::input_parameter< int >::type n_iterations_arg(n_iterations_argSEXP);
    Rcpp::traits::input_parameter< int >::type n_subtypes_arg(n_subtypes_argSEXP);
    Rcpp::traits::input_parameter< int >::type n_subjects_arg(n_subjects_argSEXP);
    Rcpp::traits::input_parameter< int >::type n_data_arg(n_data_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wp_current_arg(wp_current_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type tp_current_arg(tp_current_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type dp_current_arg(dp_current_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wr_current_arg(wr_current_argSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type model_current_arg(model_current_argSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_arg(sigma_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wp_mean_arg(wp_mean_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wp_sd_arg(wp_sd_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type tp_sd_arg(tp_sd_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type dp_mean_arg(dp_mean_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type dp_sd_arg(dp_sd_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wr_mean_arg(wr_mean_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wr_sd_arg(wr_sd_argSEXP);
    Rcpp::traits::input_parameter< double >::type wp_max_arg(wp_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type wr_max_arg(wr_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type wpmean_max_arg(wpmean_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type dpmean_max_arg(dpmean_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type wrmean_max_arg(wrmean_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type wpsd_max_arg(wpsd_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type tpsd_max_arg(tpsd_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type dpsd_max_arg(dpsd_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type wrsd_max_arg(wrsd_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_max_arg(sigma_max_argSEXP);
    Rcpp::traits::input_parameter< double >::type wpsd_min_arg(wpsd_min_argSEXP);
    Rcpp::traits::input_parameter< double >::type tpsd_min_arg(tpsd_min_argSEXP);
    Rcpp::traits::input_parameter< double >::type dpsd_min_arg(dpsd_min_argSEXP);
    Rcpp::traits::input_parameter< double >::type wrsd_min_arg(wrsd_min_argSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_min_arg(sigma_min_argSEXP);
    Rcpp::traits::input_parameter< double >::type p_model_1_arg(p_model_1_argSEXP);
    Rcpp::traits::input_parameter< double >::type p_model_2_arg(p_model_2_argSEXP);
    Rcpp::traits::input_parameter< double >::type p_model_3_arg(p_model_3_argSEXP);
    Rcpp::traits::input_parameter< double >::type wpmean_mean_arg(wpmean_mean_argSEXP);
    Rcpp::traits::input_parameter< double >::type wpmean_sd_arg(wpmean_sd_argSEXP);
    Rcpp::traits::input_parameter< double >::type dpmean_mean_arg(dpmean_mean_argSEXP);
    Rcpp::traits::input_parameter< double >::type dpmean_sd_arg(dpmean_sd_argSEXP);
    Rcpp::traits::input_parameter< double >::type wrmean_mean_arg(wrmean_mean_argSEXP);
    Rcpp::traits::input_parameter< double >::type wrmean_sd_arg(wrmean_sd_argSEXP);
    Rcpp::traits::input_parameter< double >::type wpsd_scale_arg(wpsd_scale_argSEXP);
    Rcpp::traits::input_parameter< double >::type tpsd_scale_arg(tpsd_scale_argSEXP);
    Rcpp::traits::input_parameter< double >::type dpsd_scale_arg(dpsd_scale_argSEXP);
    Rcpp::traits::input_parameter< double >::type wrsd_scale_arg(wrsd_scale_argSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_scale_arg(sigma_scale_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wp_mean_sf_arg(wp_mean_sf_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wp_sd_sf_arg(wp_sd_sf_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type tp_sd_sf_arg(tp_sd_sf_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type dp_mean_sf_arg(dp_mean_sf_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type dp_sd_sf_arg(dp_sd_sf_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wr_mean_sf_arg(wr_mean_sf_argSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type wr_sd_sf_arg(wr_sd_sf_argSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_sf_arg(sigma_sf_argSEXP);
    Rcpp::traits::input_parameter< double >::type wp_sf_arg(wp_sf_argSEXP);
    Rcpp::traits::input_parameter< double >::type tp_sf_arg(tp_sf_argSEXP);
    Rcpp::traits::input_parameter< double >::type dp_sf_arg(dp_sf_argSEXP);
    Rcpp::traits::input_parameter< double >::type wr_sf_arg(wr_sf_argSEXP);
    Rcpp::traits::input_parameter< double >::type seed_arg(seed_argSEXP);
    rjmcmc_r(output_dir, index_arg, viral_load_arg, time_arg, subtype_arg, t_first_positive_arg, t_last_positive_arg, t_first_test_arg, t_last_test_arg, n_positive_tests_arg, lod_arg, sensitivity_arg, n_iterations_arg, n_subtypes_arg, n_subjects_arg, n_data_arg, wp_current_arg, tp_current_arg, dp_current_arg, wr_current_arg, model_current_arg, sigma_arg, wp_mean_arg, wp_sd_arg, tp_sd_arg, dp_mean_arg, dp_sd_arg, wr_mean_arg, wr_sd_arg, wp_max_arg, wr_max_arg, wpmean_max_arg, dpmean_max_arg, wrmean_max_arg, wpsd_max_arg, tpsd_max_arg, dpsd_max_arg, wrsd_max_arg, sigma_max_arg, wpsd_min_arg, tpsd_min_arg, dpsd_min_arg, wrsd_min_arg, sigma_min_arg, p_model_1_arg, p_model_2_arg, p_model_3_arg, wpmean_mean_arg, wpmean_sd_arg, dpmean_mean_arg, dpmean_sd_arg, wrmean_mean_arg, wrmean_sd_arg, wpsd_scale_arg, tpsd_scale_arg, dpsd_scale_arg, wrsd_scale_arg, sigma_scale_arg, wp_mean_sf_arg, wp_sd_sf_arg, tp_sd_sf_arg, dp_mean_sf_arg, dp_sd_sf_arg, wr_mean_sf_arg, wr_sd_sf_arg, sigma_sf_arg, wp_sf_arg, tp_sf_arg, dp_sf_arg, wr_sf_arg, seed_arg);
    return R_NilValue;
END_RCPP
}
// test_normal_pdf
void test_normal_pdf();
RcppExport SEXP _ViralLoadRJMCMC_test_normal_pdf() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_normal_pdf();
    return R_NilValue;
END_RCPP
}
// test_normal_cdf
void test_normal_cdf();
RcppExport SEXP _ViralLoadRJMCMC_test_normal_cdf() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_normal_cdf();
    return R_NilValue;
END_RCPP
}
// test_exp_pdf
void test_exp_pdf();
RcppExport SEXP _ViralLoadRJMCMC_test_exp_pdf() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_exp_pdf();
    return R_NilValue;
END_RCPP
}
// test_exp_cdf
void test_exp_cdf();
RcppExport SEXP _ViralLoadRJMCMC_test_exp_cdf() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_exp_cdf();
    return R_NilValue;
END_RCPP
}
// test_rnorm_boost
double test_rnorm_boost(double seed_arg);
RcppExport SEXP _ViralLoadRJMCMC_test_rnorm_boost(SEXP seed_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type seed_arg(seed_argSEXP);
    rcpp_result_gen = Rcpp::wrap(test_rnorm_boost(seed_arg));
    return rcpp_result_gen;
END_RCPP
}
// test_runif
double test_runif(double seed_arg);
RcppExport SEXP _ViralLoadRJMCMC_test_runif(SEXP seed_argSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type seed_arg(seed_argSEXP);
    rcpp_result_gen = Rcpp::wrap(test_runif(seed_arg));
    return rcpp_result_gen;
END_RCPP
}
// log_likelihood_ti
double log_likelihood_ti(double y_i, double t_i, double wp_i, double tp_i, double dp_i, double wr_i, double sigma, double sensitivity);
RcppExport SEXP _ViralLoadRJMCMC_log_likelihood_ti(SEXP y_iSEXP, SEXP t_iSEXP, SEXP wp_iSEXP, SEXP tp_iSEXP, SEXP dp_iSEXP, SEXP wr_iSEXP, SEXP sigmaSEXP, SEXP sensitivitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y_i(y_iSEXP);
    Rcpp::traits::input_parameter< double >::type t_i(t_iSEXP);
    Rcpp::traits::input_parameter< double >::type wp_i(wp_iSEXP);
    Rcpp::traits::input_parameter< double >::type tp_i(tp_iSEXP);
    Rcpp::traits::input_parameter< double >::type dp_i(dp_iSEXP);
    Rcpp::traits::input_parameter< double >::type wr_i(wr_iSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type sensitivity(sensitivitySEXP);
    rcpp_result_gen = Rcpp::wrap(log_likelihood_ti(y_i, t_i, wp_i, tp_i, dp_i, wr_i, sigma, sensitivity));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _ViralLoadRJMCMC_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// mu
double mu(double t, double wp, double tp, double dp, double wr);
RcppExport SEXP _ViralLoadRJMCMC_mu(SEXP tSEXP, SEXP wpSEXP, SEXP tpSEXP, SEXP dpSEXP, SEXP wrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type wp(wpSEXP);
    Rcpp::traits::input_parameter< double >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< double >::type dp(dpSEXP);
    Rcpp::traits::input_parameter< double >::type wr(wrSEXP);
    rcpp_result_gen = Rcpp::wrap(mu(t, wp, tp, dp, wr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ViralLoadRJMCMC_rjmcmc_r", (DL_FUNC) &_ViralLoadRJMCMC_rjmcmc_r, 71},
    {"_ViralLoadRJMCMC_test_normal_pdf", (DL_FUNC) &_ViralLoadRJMCMC_test_normal_pdf, 0},
    {"_ViralLoadRJMCMC_test_normal_cdf", (DL_FUNC) &_ViralLoadRJMCMC_test_normal_cdf, 0},
    {"_ViralLoadRJMCMC_test_exp_pdf", (DL_FUNC) &_ViralLoadRJMCMC_test_exp_pdf, 0},
    {"_ViralLoadRJMCMC_test_exp_cdf", (DL_FUNC) &_ViralLoadRJMCMC_test_exp_cdf, 0},
    {"_ViralLoadRJMCMC_test_rnorm_boost", (DL_FUNC) &_ViralLoadRJMCMC_test_rnorm_boost, 1},
    {"_ViralLoadRJMCMC_test_runif", (DL_FUNC) &_ViralLoadRJMCMC_test_runif, 1},
    {"_ViralLoadRJMCMC_log_likelihood_ti", (DL_FUNC) &_ViralLoadRJMCMC_log_likelihood_ti, 8},
    {"_ViralLoadRJMCMC_rcpp_hello_world", (DL_FUNC) &_ViralLoadRJMCMC_rcpp_hello_world, 0},
    {"_ViralLoadRJMCMC_mu", (DL_FUNC) &_ViralLoadRJMCMC_mu, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ViralLoadRJMCMC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
