# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rjmcmc_r <- function(output_dir, index_arg, viral_load_arg, time_arg, subtype_arg, t_first_positive_arg, t_last_positive_arg, t_first_test_arg, t_last_test_arg, n_positive_tests_arg, lod_arg, sensitivity_arg, n_iterations_arg, n_subtypes_arg, n_subjects_arg, n_data_arg, wp_current_arg, tp_current_arg, dp_current_arg, wr_current_arg, model_current_arg, sigma_arg, wp_mean_arg, wp_sd_arg, tp_sd_arg, dp_mean_arg, dp_sd_arg, wr_mean_arg, wr_sd_arg, wp_max_arg, wr_max_arg, wpmean_max_arg, dpmean_max_arg, wrmean_max_arg, wpsd_max_arg, tpsd_max_arg, dpsd_max_arg, wrsd_max_arg, sigma_max_arg, wpsd_min_arg, tpsd_min_arg, dpsd_min_arg, wrsd_min_arg, sigma_min_arg, p_model_1_arg, p_model_2_arg, p_model_3_arg, wpmean_mean_arg, wpmean_sd_arg, dpmean_mean_arg, dpmean_sd_arg, wrmean_mean_arg, wrmean_sd_arg, wpsd_scale_arg, tpsd_scale_arg, dpsd_scale_arg, wrsd_scale_arg, sigma_scale_arg, wp_mean_sf_arg, wp_sd_sf_arg, tp_sd_sf_arg, dp_mean_sf_arg, dp_sd_sf_arg, wr_mean_sf_arg, wr_sd_sf_arg, sigma_sf_arg, wp_sf_arg, tp_sf_arg, dp_sf_arg, wr_sf_arg, seed_arg) {
    invisible(.Call(`_ViralLoadRJMCMC_rjmcmc_r`, output_dir, index_arg, viral_load_arg, time_arg, subtype_arg, t_first_positive_arg, t_last_positive_arg, t_first_test_arg, t_last_test_arg, n_positive_tests_arg, lod_arg, sensitivity_arg, n_iterations_arg, n_subtypes_arg, n_subjects_arg, n_data_arg, wp_current_arg, tp_current_arg, dp_current_arg, wr_current_arg, model_current_arg, sigma_arg, wp_mean_arg, wp_sd_arg, tp_sd_arg, dp_mean_arg, dp_sd_arg, wr_mean_arg, wr_sd_arg, wp_max_arg, wr_max_arg, wpmean_max_arg, dpmean_max_arg, wrmean_max_arg, wpsd_max_arg, tpsd_max_arg, dpsd_max_arg, wrsd_max_arg, sigma_max_arg, wpsd_min_arg, tpsd_min_arg, dpsd_min_arg, wrsd_min_arg, sigma_min_arg, p_model_1_arg, p_model_2_arg, p_model_3_arg, wpmean_mean_arg, wpmean_sd_arg, dpmean_mean_arg, dpmean_sd_arg, wrmean_mean_arg, wrmean_sd_arg, wpsd_scale_arg, tpsd_scale_arg, dpsd_scale_arg, wrsd_scale_arg, sigma_scale_arg, wp_mean_sf_arg, wp_sd_sf_arg, tp_sd_sf_arg, dp_mean_sf_arg, dp_sd_sf_arg, wr_mean_sf_arg, wr_sd_sf_arg, sigma_sf_arg, wp_sf_arg, tp_sf_arg, dp_sf_arg, wr_sf_arg, seed_arg))
}

test_normal_pdf <- function() {
    invisible(.Call(`_ViralLoadRJMCMC_test_normal_pdf`))
}

test_normal_cdf <- function() {
    invisible(.Call(`_ViralLoadRJMCMC_test_normal_cdf`))
}

test_exp_pdf <- function() {
    invisible(.Call(`_ViralLoadRJMCMC_test_exp_pdf`))
}

test_exp_cdf <- function() {
    invisible(.Call(`_ViralLoadRJMCMC_test_exp_cdf`))
}

test_rnorm_boost <- function(seed_arg) {
    .Call(`_ViralLoadRJMCMC_test_rnorm_boost`, seed_arg)
}

test_runif <- function(seed_arg) {
    .Call(`_ViralLoadRJMCMC_test_runif`, seed_arg)
}

log_likelihood_ti <- function(y_i, t_i, wp_i, tp_i, dp_i, wr_i, sigma, sensitivity) {
    .Call(`_ViralLoadRJMCMC_log_likelihood_ti`, y_i, t_i, wp_i, tp_i, dp_i, wr_i, sigma, sensitivity)
}

rcpp_hello_world <- function() {
    .Call(`_ViralLoadRJMCMC_rcpp_hello_world`)
}

mu <- function(t, wp, tp, dp, wr) {
    .Call(`_ViralLoadRJMCMC_mu`, t, wp, tp, dp, wr)
}

