# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_normal_pdf <- function() {
    invisible(.Call(`_ViralLoadRJMCMC_test_normal_pdf`))
}

test_normal_cdf <- function() {
    invisible(.Call(`_ViralLoadRJMCMC_test_normal_cdf`))
}

test_exp_pdf <- function() {
    invisible(.Call(`_ViralLoadRJMCMC_test_exp_pdf`))
}

test_exp_cdf <- function() {
    invisible(.Call(`_ViralLoadRJMCMC_test_exp_cdf`))
}

log_likelihood_ti <- function(y_i, t_i, wp_i, tp_i, dp_i, wr_i, sigma, sensitivity) {
    .Call(`_ViralLoadRJMCMC_log_likelihood_ti`, y_i, t_i, wp_i, tp_i, dp_i, wr_i, sigma, sensitivity)
}

log_likelihood <- function(viral_data, current_data, current_parameters, settings) {
    .Call(`_ViralLoadRJMCMC_log_likelihood`, viral_data, current_data, current_parameters, settings)
}

rcpp_hello_world <- function() {
    .Call(`_ViralLoadRJMCMC_rcpp_hello_world`)
}

mu <- function(t, wp, tp, dp, wr) {
    .Call(`_ViralLoadRJMCMC_mu`, t, wp, tp, dp, wr)
}

